// <auto-generated> welder C#/.NET native shim. Do not edit -
// regenerate via the welder_csharp_generate_bindings() target.
// Compiled with reflection against the same welded header the
// generator saw: thunk bodies SPLICE the exact member reflection
// (re-derived by the shared lookup layer), so no C++ type is
// respelled here - only the C-ABI wire types are text.
#include <cstdint>
#include <welder/vocabulary.hpp>
#include "cases.hpp"
#include <welder/rods/csharp/shim_support.hpp>

namespace wcs = ::welder::rods::csharp;

struct welder_dir_csharp_cases_Shape final : ::csharp_cases::Shape {
    using ::csharp_cases::Shape::Shape;
    void* wcs_ctx{nullptr};
    std::uint64_t wcs_mask{0};
    struct wcs_table_t {
        void (*release)(void*);
        const char* (*s0)(void*, welder_error*);
        std::int32_t (*s1)(void*, welder_error*);
    };
    static inline wcs_table_t wcs_tbl{};
    ~welder_dir_csharp_cases_Shape() override { if (wcs_ctx && wcs_tbl.release) wcs_tbl.release(wcs_ctx); }
    [: ::std::meta::return_type_of(wcs::director_slot(^^::csharp_cases::Shape, 0)) :] name() const override {
        if (wcs_ctx && (wcs_mask & (1ull << 0)) && wcs_tbl.s0) {
            welder_error _e{0, nullptr};
            auto _r = wcs_tbl.s0(wcs_ctx, &_e);
            if (_e.code != 0) wcs::shim::rethrow_managed(&_e);
            return wcs::shim::from_wire_return<::std::meta::return_type_of(wcs::director_slot(^^::csharp_cases::Shape, 0))>(_r);
        }
        return ::csharp_cases::Shape::name();
    }
    [: ::std::meta::return_type_of(wcs::director_slot(^^::csharp_cases::Shape, 1)) :] sides() const override {
        if (wcs_ctx && (wcs_mask & (1ull << 1)) && wcs_tbl.s1) {
            welder_error _e{0, nullptr};
            auto _r = wcs_tbl.s1(wcs_ctx, &_e);
            if (_e.code != 0) wcs::shim::rethrow_managed(&_e);
            return wcs::shim::from_wire_return<::std::meta::return_type_of(wcs::director_slot(^^::csharp_cases::Shape, 1))>(_r);
        }
        return ::csharp_cases::Shape::sides();
    }
};

extern "C" {

void welder_csharp_cases_Point_destroy(void* self) { wcs::shim::destroy<^^::csharp_cases::Point>(self); }

void* welder_csharp_cases_Point_new_default(welder_error* err) { return wcs::shim::default_construct<^^::csharp_cases::Point>(err); }

void* welder_csharp_cases_Point_new_1(std::int32_t a0, std::int32_t a1, welder_error* err) { return wcs::shim::construct<^^::csharp_cases::Point, wcs::ctor_at(^^::csharp_cases::Point, 1)>(err, a0, a1); }

void* welder_csharp_cases_Point_clone(void* self, welder_error* err) { return wcs::shim::clone<^^::csharp_cases::Point>(self, err); }

static_assert(wcs::shim::nsdm_offset<^^::csharp_cases::Point>(0) == 0, "welder: erased-field offset drift: x");

static_assert(wcs::shim::nsdm_offset<^^::csharp_cases::Point>(1) == 4, "welder: erased-field offset drift: y");

static_assert(wcs::shim::nsdm_offset<^^::csharp_cases::Point>(2) == 8, "welder: erased-field offset drift: stamp");

std::int32_t welder_csharp_cases_Point_m_sum_0(void* self, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Point, wcs::named_member(^^::csharp_cases::Point, "sum", 0)>(self, err); }

void welder_csharp_cases_Point_m_offset_0(void* self, std::int32_t a0, std::int32_t a1, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Point, wcs::named_member(^^::csharp_cases::Point, "offset", 0)>(self, err, a0, a1); }

void welder_csharp_cases_Point_m_offset_1(void* self, std::int32_t a0, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Point, wcs::named_member(^^::csharp_cases::Point, "offset", 1)>(self, err, a0); }

const char* welder_csharp_cases_Point_m_label_0(void* self, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Point, wcs::named_member(^^::csharp_cases::Point, "label", 0)>(self, err); }

std::int32_t welder_csharp_cases_Point_m_hue_0(void* self, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Point, wcs::named_member(^^::csharp_cases::Point, "hue", 0)>(self, err); }

void* welder_csharp_cases_Point_m_translated_0(void* self, std::int32_t a0, std::int32_t a1, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Point, wcs::named_member(^^::csharp_cases::Point, "translated", 0)>(self, err, a0, a1); }

void* welder_csharp_cases_Point_s_origin_0(welder_error* err) { return wcs::shim::function<wcs::named_member(^^::csharp_cases::Point, "origin", 0)>(err); }

void welder_csharp_cases_Point_m_explode_0(void* self, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Point, wcs::named_member(^^::csharp_cases::Point, "explode", 0)>(self, err); }

std::int32_t welder_csharp_cases_Point_pget_Depth(void* self, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Point, wcs::named_member(^^::csharp_cases::Point, "depth", 0)>(self, err); }

void welder_csharp_cases_Point_pset_Depth(void* self, std::int32_t v, welder_error* err) { (void)wcs::shim::method<^^::csharp_cases::Point, wcs::named_member(^^::csharp_cases::Point, "depth", 1)>(self, err, v); }

void* welder_csharp_cases_Point_op_plus_b_0(void* self, void* a0, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Point, wcs::named_operator(^^::csharp_cases::Point, std::meta::operators::op_plus, false, 0)>(self, err, a0); }

bool welder_csharp_cases_Point_op_equals_equals_b_0(void* self, void* a0, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Point, wcs::named_operator(^^::csharp_cases::Point, std::meta::operators::op_equals_equals, false, 0)>(self, err, a0); }

void welder_csharp_cases_Size_destroy(void* self) { wcs::shim::destroy<^^::csharp_cases::Size>(self); }

void* welder_csharp_cases_Size_new_default(welder_error* err) { return wcs::shim::default_construct<^^::csharp_cases::Size>(err); }

void* welder_csharp_cases_Size_new_agg(std::int32_t a0, std::int32_t a1, welder_error* err) { return wcs::shim::aggregate_construct<^^::csharp_cases::Size>(err, a0, a1); }

void* welder_csharp_cases_Size_clone(void* self, welder_error* err) { return wcs::shim::clone<^^::csharp_cases::Size>(self, err); }

static_assert(wcs::shim::nsdm_offset<^^::csharp_cases::Size>(0) == 0, "welder: erased-field offset drift: width");

static_assert(wcs::shim::nsdm_offset<^^::csharp_cases::Size>(1) == 4, "welder: erased-field offset drift: height");

void welder_csharp_cases_Holder_destroy(void* self) { wcs::shim::destroy<^^::csharp_cases::Holder>(self); }

void* welder_csharp_cases_Holder_new_default(welder_error* err) { return wcs::shim::default_construct<^^::csharp_cases::Holder>(err); }

void* welder_csharp_cases_Holder_clone(void* self, welder_error* err) { return wcs::shim::clone<^^::csharp_cases::Holder>(self, err); }

void* welder_csharp_cases_Holder_m_item_0(void* self, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Holder, wcs::named_member(^^::csharp_cases::Holder, "item", 0)>(self, err); }

void* welder_csharp_cases_Holder_m_item_copy_0(void* self, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Holder, wcs::named_member(^^::csharp_cases::Holder, "item_copy", 0)>(self, err); }

void* welder_csharp_cases_Holder_m_peek_0(void* self, bool a0, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Holder, wcs::named_member(^^::csharp_cases::Holder, "peek", 0)>(self, err, a0); }

std::int32_t welder_csharp_cases_Holder_m_item_x_0(void* self, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Holder, wcs::named_member(^^::csharp_cases::Holder, "item_x", 0)>(self, err); }

void* welder_csharp_cases_f_make_point_0(std::int32_t a0, std::int32_t a1, welder_error* err) { return wcs::shim::function<wcs::named_member(^^::csharp_cases, "make_point", 0)>(err, a0, a1); }

welder_seq_wire welder_csharp_cases_f_tagged_0(std::int32_t a0, welder_error* err) { return wcs::shim::function<wcs::named_member(^^::csharp_cases, "tagged", 0)>(err, a0); }

std::int64_t welder_csharp_cases_f_pair_sum_0(const welder_opt_wire* a0, welder_error* err) { return wcs::shim::function<wcs::named_member(^^::csharp_cases, "pair_sum", 0)>(err, a0); }

welder_seq_wire welder_csharp_cases_f_bundle_0(welder_error* err) { return wcs::shim::function<wcs::named_member(^^::csharp_cases, "bundle", 0)>(err); }

void welder_csharp_cases_f_reject_0(std::int32_t a0, welder_error* err) { return wcs::shim::function<wcs::named_member(^^::csharp_cases, "reject", 0)>(err, a0); }

void welder_csharp_cases_Segment_destroy(void* self) { wcs::shim::destroy<^^::csharp_cases::Segment>(self); }

void* welder_csharp_cases_Segment_new_default(welder_error* err) { return wcs::shim::default_construct<^^::csharp_cases::Segment>(err); }

void* welder_csharp_cases_Segment_new_1(void* a0, void* a1, welder_error* err) { return wcs::shim::construct<^^::csharp_cases::Segment, wcs::ctor_at(^^::csharp_cases::Segment, 1)>(err, a0, a1); }

void* welder_csharp_cases_Segment_clone(void* self, welder_error* err) { return wcs::shim::clone<^^::csharp_cases::Segment>(self, err); }

static_assert(wcs::shim::nsdm_offset<^^::csharp_cases::Segment>(0) == 0, "welder: erased-field offset drift: start");

void welder_csharp_cases_Segment_set_start(void* self, void* v, welder_error* err) { return wcs::shim::field_set<^^::csharp_cases::Segment, wcs::named_field(^^::csharp_cases::Segment, "start")>(self, err, v); }

static_assert(wcs::shim::nsdm_offset<^^::csharp_cases::Segment>(1) == 16, "welder: erased-field offset drift: end");

void welder_csharp_cases_Segment_set_end(void* self, void* v, welder_error* err) { return wcs::shim::field_set<^^::csharp_cases::Segment, wcs::named_field(^^::csharp_cases::Segment, "end")>(self, err, v); }

std::int32_t welder_csharp_cases_Segment_m_span_0(void* self, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Segment, wcs::named_member(^^::csharp_cases::Segment, "span", 0)>(self, err); }

bool welder_csharp_cases_Segment_m_degenerate_0(void* self, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Segment, wcs::named_member(^^::csharp_cases::Segment, "degenerate", 0)>(self, err); }

std::int32_t welder_csharp_cases_f_add_0(std::int32_t a0, std::int32_t a1, welder_error* err) { return wcs::shim::function<wcs::named_member(^^::csharp_cases, "add", 0)>(err, a0, a1); }

const char* welder_csharp_cases_f_greet_0(const char* a0, welder_error* err) { return wcs::shim::function<wcs::named_member(^^::csharp_cases, "greet", 0)>(err, a0); }

std::int32_t welder_csharp_cases_v_answer_get(welder_error* err) { return wcs::shim::var_get<wcs::named_field(^^::csharp_cases, "answer")>(err); }

void welder_csharp_cases_v_answer_set(std::int32_t v, welder_error* err) { return wcs::shim::var_set<wcs::named_field(^^::csharp_cases, "answer")>(err, v); }

double welder_csharp_cases_v_golden_get(welder_error* err) { return wcs::shim::var_get<wcs::named_field(^^::csharp_cases, "golden")>(err); }

void welder_csharp_cases_Animal_destroy(void* self) { wcs::shim::destroy<^^::csharp_cases::Animal>(self); }

void* welder_csharp_cases_Animal_new_default(welder_error* err) { return wcs::shim::default_construct<^^::csharp_cases::Animal>(err); }

void* welder_csharp_cases_Animal_clone(void* self, welder_error* err) { return wcs::shim::clone<^^::csharp_cases::Animal>(self, err); }

static_assert(wcs::shim::nsdm_offset<^^::csharp_cases::Animal>(0) == 0, "welder: erased-field offset drift: age");

const char* welder_csharp_cases_Animal_m_kind_0(void* self, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Animal, wcs::named_member(^^::csharp_cases::Animal, "kind", 0)>(self, err); }

void welder_csharp_cases_Legged_destroy(void* self) { wcs::shim::destroy<^^::csharp_cases::Legged>(self); }

void* welder_csharp_cases_Legged_new_default(welder_error* err) { return wcs::shim::default_construct<^^::csharp_cases::Legged>(err); }

void* welder_csharp_cases_Legged_clone(void* self, welder_error* err) { return wcs::shim::clone<^^::csharp_cases::Legged>(self, err); }

static_assert(wcs::shim::nsdm_offset<^^::csharp_cases::Legged>(0) == 0, "welder: erased-field offset drift: legs");

void* welder_csharp_cases_Dog_as_csharp_cases_Animal(void* self) { return wcs::shim::upcast<^^::csharp_cases::Dog, ^^::csharp_cases::Animal>(self); }

void* welder_csharp_cases_Dog_as_csharp_cases_Legged(void* self) { return wcs::shim::upcast<^^::csharp_cases::Dog, ^^::csharp_cases::Legged>(self); }

void welder_csharp_cases_Dog_destroy(void* self) { wcs::shim::destroy<^^::csharp_cases::Dog>(self); }

void* welder_csharp_cases_Dog_new_default(welder_error* err) { return wcs::shim::default_construct<^^::csharp_cases::Dog>(err); }

void* welder_csharp_cases_Dog_clone(void* self, welder_error* err) { return wcs::shim::clone<^^::csharp_cases::Dog>(self, err); }

const char* welder_csharp_cases_Dog_m_bark_0(void* self, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Dog, wcs::named_member(^^::csharp_cases::Dog, "bark", 0)>(self, err); }

std::int32_t welder_csharp_cases_f_age_of_0(void* a0, welder_error* err) { return wcs::shim::function<wcs::named_member(^^::csharp_cases, "age_of", 0)>(err, a0); }

void welder_csharp_cases_Basket_destroy(void* self) { wcs::shim::destroy<^^::csharp_cases::Basket>(self); }

void* welder_csharp_cases_Basket_new_default(welder_error* err) { return wcs::shim::default_construct<^^::csharp_cases::Basket>(err); }

void* welder_csharp_cases_Basket_clone(void* self, welder_error* err) { return wcs::shim::clone<^^::csharp_cases::Basket>(self, err); }

void* welder_vecs_int_new(welder_error* err) { return wcs::shim::vec_new<^^int>(err); }

void welder_vecs_int_destroy(void* self) { wcs::shim::vec_destroy<^^int>(self); }

void* welder_vecs_int_data(void* self, welder_error* err) { return wcs::shim::vec_data<^^int>(self, err); }

void welder_vecs_int_fill(void* self, const void* data, std::int64_t len, welder_error* err) { wcs::shim::vec_fill<^^int>(self, data, len, err); }

std::int64_t welder_vecs_int_size(void* self, welder_error* err) { return wcs::shim::vec_size<^^int>(self, err); }

void welder_vecs_int_push(void* self, std::int32_t v, welder_error* err) { wcs::shim::vec_push<^^int>(self, v, err); }

void welder_vecs_int_clear(void* self, welder_error* err) { wcs::shim::vec_clear<^^int>(self, err); }

static_assert(wcs::shim::nsdm_offset<^^::csharp_cases::Basket>(0) == 0, "welder: erased-field offset drift: nums");

void welder_csharp_cases_Basket_set_nums(void* self, void* v, welder_error* err) { wcs::shim::field_assign<^^::csharp_cases::Basket, wcs::named_field(^^::csharp_cases::Basket, "nums")>(self, v, err); }

void* welder_arrs_double_3_new(welder_error* err) { return wcs::shim::arr_new<^^double, 3>(err); }

void welder_arrs_double_3_destroy(void* self) { wcs::shim::arr_destroy<^^double, 3>(self); }

void* welder_arrs_double_3_data(void* self, welder_error* err) { return wcs::shim::arr_data<^^double, 3>(self, err); }

void welder_arrs_double_3_fill(void* self, const void* data, std::int64_t len, welder_error* err) { wcs::shim::arr_fill<^^double, 3>(self, data, len, err); }

static_assert(wcs::shim::nsdm_offset<^^::csharp_cases::Basket>(1) == 24, "welder: erased-field offset drift: bounds");

void welder_csharp_cases_Basket_set_bounds(void* self, void* v, welder_error* err) { wcs::shim::field_assign<^^::csharp_cases::Basket, wcs::named_field(^^::csharp_cases::Basket, "bounds")>(self, v, err); }

void* welder_vecs_csharp_cases_Level_new(welder_error* err) { return wcs::shim::vec_new<^^::csharp_cases::Level>(err); }

void welder_vecs_csharp_cases_Level_destroy(void* self) { wcs::shim::vec_destroy<^^::csharp_cases::Level>(self); }

void* welder_vecs_csharp_cases_Level_data(void* self, welder_error* err) { return wcs::shim::vec_data<^^::csharp_cases::Level>(self, err); }

void welder_vecs_csharp_cases_Level_fill(void* self, const void* data, std::int64_t len, welder_error* err) { wcs::shim::vec_fill<^^::csharp_cases::Level>(self, data, len, err); }

std::int64_t welder_vecs_csharp_cases_Level_size(void* self, welder_error* err) { return wcs::shim::vec_size<^^::csharp_cases::Level>(self, err); }

void welder_vecs_csharp_cases_Level_push(void* self, std::uint8_t v, welder_error* err) { wcs::shim::vec_push<^^::csharp_cases::Level>(self, v, err); }

void welder_vecs_csharp_cases_Level_clear(void* self, welder_error* err) { wcs::shim::vec_clear<^^::csharp_cases::Level>(self, err); }

static_assert(wcs::shim::nsdm_offset<^^::csharp_cases::Basket>(2) == 48, "welder: erased-field offset drift: levels");

void welder_csharp_cases_Basket_set_levels(void* self, void* v, welder_error* err) { wcs::shim::field_assign<^^::csharp_cases::Basket, wcs::named_field(^^::csharp_cases::Basket, "levels")>(self, v, err); }

welder_opt_wire welder_csharp_cases_Basket_get_label(void* self, welder_error* err) { return wcs::shim::field_get<^^::csharp_cases::Basket, wcs::named_field(^^::csharp_cases::Basket, "label")>(self, err); }

void welder_csharp_cases_Basket_set_label(void* self, welder_opt_wire v, welder_error* err) { return wcs::shim::field_set<^^::csharp_cases::Basket, wcs::named_field(^^::csharp_cases::Basket, "label")>(self, err, v); }

welder_opt_wire welder_csharp_cases_Basket_m_find_0(void* self, std::int32_t a0, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Basket, wcs::named_member(^^::csharp_cases::Basket, "find", 0)>(self, err, a0); }

std::int64_t welder_csharp_cases_Basket_m_total_0(void* self, welder_seq_wire a0, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Basket, wcs::named_member(^^::csharp_cases::Basket, "total", 0)>(self, err, a0); }

welder_seq_wire welder_csharp_cases_Basket_m_triple_0(void* self, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Basket, wcs::named_member(^^::csharp_cases::Basket, "triple", 0)>(self, err); }

void welder_csharp_cases_Basket_m_set_triple_0(void* self, welder_seq_wire a0, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Basket, wcs::named_member(^^::csharp_cases::Basket, "set_triple", 0)>(self, err, a0); }

double welder_csharp_cases_Basket_m_trip_sum_0(void* self, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Basket, wcs::named_member(^^::csharp_cases::Basket, "trip_sum", 0)>(self, err); }

welder_opt_wire welder_csharp_cases_f_maybe_point_0(bool a0, welder_error* err) { return wcs::shim::function<wcs::named_member(^^::csharp_cases, "maybe_point", 0)>(err, a0); }

welder_opt_wire welder_csharp_cases_f_maybe_level_0(bool a0, welder_error* err) { return wcs::shim::function<wcs::named_member(^^::csharp_cases, "maybe_level", 0)>(err, a0); }

void welder_csharp_cases_Route_destroy(void* self) { wcs::shim::destroy<^^::csharp_cases::Route>(self); }

void* welder_csharp_cases_Route_new_default(welder_error* err) { return wcs::shim::default_construct<^^::csharp_cases::Route>(err); }

void* welder_csharp_cases_Route_clone(void* self, welder_error* err) { return wcs::shim::clone<^^::csharp_cases::Route>(self, err); }

void* welder_vec_csharp_cases_Point_new(welder_error* err) { return wcs::shim::vec_new<^^::csharp_cases::Point>(err); }

void welder_vec_csharp_cases_Point_destroy(void* self) { wcs::shim::vec_destroy<^^::csharp_cases::Point>(self); }

std::int64_t welder_vec_csharp_cases_Point_size(void* self, welder_error* err) { return wcs::shim::vec_size<^^::csharp_cases::Point>(self, err); }

void* welder_vec_csharp_cases_Point_get(void* self, std::int64_t i, welder_error* err) { return wcs::shim::vec_get<^^::csharp_cases::Point>(self, i, err); }

void welder_vec_csharp_cases_Point_set(void* self, std::int64_t i, void* elem, welder_error* err) { wcs::shim::vec_set<^^::csharp_cases::Point>(self, i, elem, err); }

void welder_vec_csharp_cases_Point_add(void* self, void* elem, welder_error* err) { wcs::shim::vec_add<^^::csharp_cases::Point>(self, elem, err); }

void welder_vec_csharp_cases_Point_clear(void* self, welder_error* err) { wcs::shim::vec_clear<^^::csharp_cases::Point>(self, err); }

static_assert(wcs::shim::nsdm_offset<^^::csharp_cases::Route>(0) == 0, "welder: erased-field offset drift: stops");

void welder_csharp_cases_Route_set_stops(void* self, void* v, welder_error* err) { return wcs::shim::field_set<^^::csharp_cases::Route, wcs::named_field(^^::csharp_cases::Route, "stops")>(self, err, v); }

std::int32_t welder_csharp_cases_Route_m_stop_count_0(void* self, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Route, wcs::named_member(^^::csharp_cases::Route, "stop_count", 0)>(self, err); }

void* welder_csharp_cases_Route_m_reversed_0(void* self, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Route, wcs::named_member(^^::csharp_cases::Route, "reversed", 0)>(self, err); }

std::int32_t welder_csharp_cases_Route_m_total_x_0(void* self, void* a0, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Route, wcs::named_member(^^::csharp_cases::Route, "total_x", 0)>(self, err, a0); }

void welder_csharp_cases_Depot_destroy(void* self) { wcs::shim::destroy<^^::csharp_cases::Depot>(self); }

void* welder_csharp_cases_Depot_new_default(welder_error* err) { return wcs::shim::default_construct<^^::csharp_cases::Depot>(err); }

void* welder_csharp_cases_Depot_clone(void* self, welder_error* err) { return wcs::shim::clone<^^::csharp_cases::Depot>(self, err); }

void* welder_map_str_csharp_cases_Point_new(welder_error* err) { return wcs::shim::map_new<true, ^^std::string, ^^::csharp_cases::Point>(err); }

void welder_map_str_csharp_cases_Point_destroy(void* self) { wcs::shim::map_destroy<true, ^^std::string, ^^::csharp_cases::Point>(self); }

std::int64_t welder_map_str_csharp_cases_Point_size(void* self, welder_error* err) { return wcs::shim::map_size<true, ^^std::string, ^^::csharp_cases::Point>(self, err); }

bool welder_map_str_csharp_cases_Point_contains(void* self, const char* k, welder_error* err) { return wcs::shim::map_contains<true, ^^std::string, ^^::csharp_cases::Point>(self, k, err); }

void* welder_map_str_csharp_cases_Point_get(void* self, const char* k, welder_error* err) { return wcs::shim::map_get<true, ^^std::string, ^^::csharp_cases::Point>(self, k, err); }

void welder_map_str_csharp_cases_Point_set(void* self, const char* k, void* v, welder_error* err) { wcs::shim::map_set<true, ^^std::string, ^^::csharp_cases::Point>(self, k, v, err); }

bool welder_map_str_csharp_cases_Point_remove(void* self, const char* k, welder_error* err) { return wcs::shim::map_remove<true, ^^std::string, ^^::csharp_cases::Point>(self, k, err); }

void welder_map_str_csharp_cases_Point_clear(void* self, welder_error* err) { wcs::shim::map_clear<true, ^^std::string, ^^::csharp_cases::Point>(self, err); }

static_assert(wcs::shim::nsdm_offset<^^::csharp_cases::Depot>(0) == 0, "welder: erased-field offset drift: sites");

void welder_csharp_cases_Depot_set_sites(void* self, void* v, welder_error* err) { return wcs::shim::field_set<^^::csharp_cases::Depot, wcs::named_field(^^::csharp_cases::Depot, "sites")>(self, err, v); }

void* welder_umap_int_str_new(welder_error* err) { return wcs::shim::map_new<false, ^^int, ^^std::string>(err); }

void welder_umap_int_str_destroy(void* self) { wcs::shim::map_destroy<false, ^^int, ^^std::string>(self); }

std::int64_t welder_umap_int_str_size(void* self, welder_error* err) { return wcs::shim::map_size<false, ^^int, ^^std::string>(self, err); }

bool welder_umap_int_str_contains(void* self, std::int32_t k, welder_error* err) { return wcs::shim::map_contains<false, ^^int, ^^std::string>(self, k, err); }

const char* welder_umap_int_str_get(void* self, std::int32_t k, welder_error* err) { return wcs::shim::map_get<false, ^^int, ^^std::string>(self, k, err); }

void welder_umap_int_str_set(void* self, std::int32_t k, const char* v, welder_error* err) { wcs::shim::map_set<false, ^^int, ^^std::string>(self, k, v, err); }

bool welder_umap_int_str_remove(void* self, std::int32_t k, welder_error* err) { return wcs::shim::map_remove<false, ^^int, ^^std::string>(self, k, err); }

void welder_umap_int_str_clear(void* self, welder_error* err) { wcs::shim::map_clear<false, ^^int, ^^std::string>(self, err); }

static_assert(wcs::shim::nsdm_offset<^^::csharp_cases::Depot>(1) == 48, "welder: erased-field offset drift: labels");

void welder_csharp_cases_Depot_set_labels(void* self, void* v, welder_error* err) { return wcs::shim::field_set<^^::csharp_cases::Depot, wcs::named_field(^^::csharp_cases::Depot, "labels")>(self, err, v); }

std::int32_t welder_csharp_cases_Depot_m_site_count_0(void* self, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Depot, wcs::named_member(^^::csharp_cases::Depot, "site_count", 0)>(self, err); }

std::int64_t welder_csharp_cases_Depot_m_label_keys_0(void* self, void* a0, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Depot, wcs::named_member(^^::csharp_cases::Depot, "label_keys", 0)>(self, err, a0); }

void welder_csharp_cases_Cable_destroy(void* self) { wcs::shim::destroy<^^::csharp_cases::Cable>(self); }

void* welder_csharp_cases_Cable_new_default(welder_error* err) { return wcs::shim::default_construct<^^::csharp_cases::Cable>(err); }

void* welder_csharp_cases_Cable_clone(void* self, welder_error* err) { return wcs::shim::clone<^^::csharp_cases::Cable>(self, err); }

void* welder_arr2_csharp_cases_Point_new(welder_error* err) { return wcs::shim::arr_new<^^::csharp_cases::Point, 2>(err); }

void welder_arr2_csharp_cases_Point_destroy(void* self) { wcs::shim::arr_destroy<^^::csharp_cases::Point, 2>(self); }

void* welder_arr2_csharp_cases_Point_get(void* self, std::int64_t i, welder_error* err) { return wcs::shim::arr_get<^^::csharp_cases::Point, 2>(self, i, err); }

void welder_arr2_csharp_cases_Point_set(void* self, std::int64_t i, void* elem, welder_error* err) { wcs::shim::arr_set<^^::csharp_cases::Point, 2>(self, i, elem, err); }

static_assert(wcs::shim::nsdm_offset<^^::csharp_cases::Cable>(0) == 0, "welder: erased-field offset drift: ends");

void welder_csharp_cases_Cable_set_ends(void* self, void* v, welder_error* err) { return wcs::shim::field_set<^^::csharp_cases::Cable, wcs::named_field(^^::csharp_cases::Cable, "ends")>(self, err, v); }

std::int32_t welder_csharp_cases_Cable_m_span_x_0(void* self, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Cable, wcs::named_member(^^::csharp_cases::Cable, "span_x", 0)>(self, err); }

void welder_sp_csharp_cases_Point_free(void* box) { wcs::shim::sp_free<^^::csharp_cases::Point>(box); }

welder_sp_wire welder_csharp_cases_f_shared_point_0(std::int32_t a0, std::int32_t a1, welder_error* err) { return wcs::shim::function<wcs::named_member(^^::csharp_cases, "shared_point", 0)>(err, a0, a1); }

welder_sp_wire welder_csharp_cases_f_no_point_0(welder_error* err) { return wcs::shim::function<wcs::named_member(^^::csharp_cases, "no_point", 0)>(err); }

std::int32_t welder_csharp_cases_f_shared_x_0(void* a0, welder_error* err) { return wcs::shim::function<wcs::named_member(^^::csharp_cases, "shared_x", 0)>(err, a0); }

void* welder_csharp_cases_f_unique_point_0(std::int32_t a0, std::int32_t a1, welder_error* err) { return wcs::shim::function<wcs::named_member(^^::csharp_cases, "unique_point", 0)>(err, a0, a1); }

void welder_csharp_cases_Shape_dir_init(void* release, void* s0, void* s1) {
    welder_dir_csharp_cases_Shape::wcs_tbl.release = reinterpret_cast<void (*)(void*)>(release);
    welder_dir_csharp_cases_Shape::wcs_tbl.s0 = reinterpret_cast<const char* (*)(void*, welder_error*)>(s0);
    welder_dir_csharp_cases_Shape::wcs_tbl.s1 = reinterpret_cast<std::int32_t (*)(void*, welder_error*)>(s1);
}

void welder_csharp_cases_Shape_dir_bind(void* self, void* ctx, std::uint64_t mask) {
    if (auto* _d = dynamic_cast<welder_dir_csharp_cases_Shape*>(static_cast<::csharp_cases::Shape*>(self))) { _d->wcs_ctx = ctx; _d->wcs_mask = mask; }
}

void welder_csharp_cases_Shape_destroy(void* self) { wcs::shim::destroy<^^::csharp_cases::Shape>(self); }

void* welder_csharp_cases_Shape_new_default(welder_error* err) { return wcs::shim::default_construct_as<^^welder_dir_csharp_cases_Shape, ^^::csharp_cases::Shape>(err); }

void* welder_csharp_cases_Shape_clone(void* self, welder_error* err) { return wcs::shim::clone<^^::csharp_cases::Shape>(self, err); }

const char* welder_csharp_cases_Shape_m_name_0(void* self, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Shape, wcs::named_member(^^::csharp_cases::Shape, "name", 0)>(self, err); }

const char* welder_csharp_cases_Shape_m_name_0_base(void* self, welder_error* err) {
    auto* _o = static_cast<::csharp_cases::Shape*>(self);
    return wcs::shim::guarded<::std::meta::return_type_of(wcs::director_slot(^^::csharp_cases::Shape, 0))>(err, [&]() -> decltype(auto) { return _o->::csharp_cases::Shape::name(); });
}

std::int32_t welder_csharp_cases_Shape_m_sides_0(void* self, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Shape, wcs::named_member(^^::csharp_cases::Shape, "sides", 0)>(self, err); }

std::int32_t welder_csharp_cases_Shape_m_sides_0_base(void* self, welder_error* err) {
    auto* _o = static_cast<::csharp_cases::Shape*>(self);
    return wcs::shim::guarded<::std::meta::return_type_of(wcs::director_slot(^^::csharp_cases::Shape, 1))>(err, [&]() -> decltype(auto) { return _o->::csharp_cases::Shape::sides(); });
}

const char* welder_csharp_cases_Shape_m_describe_0(void* self, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Shape, wcs::named_member(^^::csharp_cases::Shape, "describe", 0)>(self, err); }

const char* welder_csharp_cases_f_describe_shape_0(void* a0, welder_error* err) { return wcs::shim::function<wcs::named_member(^^::csharp_cases, "describe_shape", 0)>(err, a0); }

void welder_csharp_cases_Machine_destroy(void* self) { wcs::shim::destroy<^^::csharp_cases::Machine>(self); }

void welder_csharp_cases_Machine_Gauge_destroy(void* self) { wcs::shim::destroy<^^::csharp_cases::Machine::Gauge>(self); }

void* welder_csharp_cases_Machine_Gauge_new_default(welder_error* err) { return wcs::shim::default_construct<^^::csharp_cases::Machine::Gauge>(err); }

void* welder_csharp_cases_Machine_Gauge_new_1(std::int32_t a0, welder_error* err) { return wcs::shim::construct<^^::csharp_cases::Machine::Gauge, wcs::ctor_at(^^::csharp_cases::Machine::Gauge, 1)>(err, a0); }

void* welder_csharp_cases_Machine_Gauge_clone(void* self, welder_error* err) { return wcs::shim::clone<^^::csharp_cases::Machine::Gauge>(self, err); }

static_assert(wcs::shim::nsdm_offset<^^::csharp_cases::Machine::Gauge>(0) == 0, "welder: erased-field offset drift: value");

void* welder_csharp_cases_Machine_new_default(welder_error* err) { return wcs::shim::default_construct<^^::csharp_cases::Machine>(err); }

void* welder_csharp_cases_Machine_clone(void* self, welder_error* err) { return wcs::shim::clone<^^::csharp_cases::Machine>(self, err); }

static_assert(wcs::shim::nsdm_offset<^^::csharp_cases::Machine>(0) == 0, "welder: erased-field offset drift: power");

static_assert(wcs::shim::nsdm_offset<^^::csharp_cases::Machine>(1) == 4, "welder: erased-field offset drift: dial");

void welder_csharp_cases_Machine_set_dial(void* self, void* v, welder_error* err) { return wcs::shim::field_set<^^::csharp_cases::Machine, wcs::named_field(^^::csharp_cases::Machine, "dial")>(self, err, v); }

void welder_csharp_cases_Machine_m_turn_on_0(void* self, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Machine, wcs::named_member(^^::csharp_cases::Machine, "turn_on", 0)>(self, err); }

void* welder_csharp_cases_Machine_m_peak_0(void* self, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Machine, wcs::named_member(^^::csharp_cases::Machine, "peak", 0)>(self, err); }

void welder_csharp_cases_Terrain_destroy(void* self) { wcs::shim::destroy<^^::csharp_cases::Terrain>(self); }

void* welder_csharp_cases_Terrain_new_default(welder_error* err) { return wcs::shim::default_construct<^^::csharp_cases::Terrain>(err); }

void* welder_csharp_cases_Terrain_clone(void* self, welder_error* err) { return wcs::shim::clone<^^::csharp_cases::Terrain>(self, err); }

void* welder_vecs_byte_new(welder_error* err) { return wcs::shim::vec_new<^^unsigned char>(err); }

void welder_vecs_byte_destroy(void* self) { wcs::shim::vec_destroy<^^unsigned char>(self); }

void* welder_vecs_byte_data(void* self, welder_error* err) { return wcs::shim::vec_data<^^unsigned char>(self, err); }

void welder_vecs_byte_fill(void* self, const void* data, std::int64_t len, welder_error* err) { wcs::shim::vec_fill<^^unsigned char>(self, data, len, err); }

std::int64_t welder_vecs_byte_size(void* self, welder_error* err) { return wcs::shim::vec_size<^^unsigned char>(self, err); }

void welder_vecs_byte_push(void* self, std::uint8_t v, welder_error* err) { wcs::shim::vec_push<^^unsigned char>(self, v, err); }

void welder_vecs_byte_clear(void* self, welder_error* err) { wcs::shim::vec_clear<^^unsigned char>(self, err); }

void* welder_vec_std_vector_unsigned_char_new(welder_error* err) { return wcs::shim::vec_new<^^::std::vector<unsigned char>>(err); }

void welder_vec_std_vector_unsigned_char_destroy(void* self) { wcs::shim::vec_destroy<^^::std::vector<unsigned char>>(self); }

std::int64_t welder_vec_std_vector_unsigned_char_size(void* self, welder_error* err) { return wcs::shim::vec_size<^^::std::vector<unsigned char>>(self, err); }

void* welder_vec_std_vector_unsigned_char_get(void* self, std::int64_t i, welder_error* err) { return wcs::shim::vec_get<^^::std::vector<unsigned char>>(self, i, err); }

void welder_vec_std_vector_unsigned_char_set(void* self, std::int64_t i, void* elem, welder_error* err) { wcs::shim::vec_set<^^::std::vector<unsigned char>>(self, i, elem, err); }

void welder_vec_std_vector_unsigned_char_add(void* self, void* elem, welder_error* err) { wcs::shim::vec_add<^^::std::vector<unsigned char>>(self, elem, err); }

void welder_vec_std_vector_unsigned_char_clear(void* self, welder_error* err) { wcs::shim::vec_clear<^^::std::vector<unsigned char>>(self, err); }

static_assert(wcs::shim::nsdm_offset<^^::csharp_cases::Terrain>(0) == 0, "welder: erased-field offset drift: layers");

void welder_csharp_cases_Terrain_set_layers(void* self, void* v, welder_error* err) { return wcs::shim::field_set<^^::csharp_cases::Terrain, wcs::named_field(^^::csharp_cases::Terrain, "layers")>(self, err, v); }

void* welder_arrs_byte_4_new(welder_error* err) { return wcs::shim::arr_new<^^unsigned char, 4>(err); }

void welder_arrs_byte_4_destroy(void* self) { wcs::shim::arr_destroy<^^unsigned char, 4>(self); }

void* welder_arrs_byte_4_data(void* self, welder_error* err) { return wcs::shim::arr_data<^^unsigned char, 4>(self, err); }

void welder_arrs_byte_4_fill(void* self, const void* data, std::int64_t len, welder_error* err) { wcs::shim::arr_fill<^^unsigned char, 4>(self, data, len, err); }

void* welder_vec_std_array_unsigned_char_4_new(welder_error* err) { return wcs::shim::vec_new<^^::std::array<unsigned char, 4>>(err); }

void welder_vec_std_array_unsigned_char_4_destroy(void* self) { wcs::shim::vec_destroy<^^::std::array<unsigned char, 4>>(self); }

std::int64_t welder_vec_std_array_unsigned_char_4_size(void* self, welder_error* err) { return wcs::shim::vec_size<^^::std::array<unsigned char, 4>>(self, err); }

void* welder_vec_std_array_unsigned_char_4_get(void* self, std::int64_t i, welder_error* err) { return wcs::shim::vec_get<^^::std::array<unsigned char, 4>>(self, i, err); }

void welder_vec_std_array_unsigned_char_4_set(void* self, std::int64_t i, void* elem, welder_error* err) { wcs::shim::vec_set<^^::std::array<unsigned char, 4>>(self, i, elem, err); }

void welder_vec_std_array_unsigned_char_4_add(void* self, void* elem, welder_error* err) { wcs::shim::vec_add<^^::std::array<unsigned char, 4>>(self, elem, err); }

void welder_vec_std_array_unsigned_char_4_clear(void* self, welder_error* err) { wcs::shim::vec_clear<^^::std::array<unsigned char, 4>>(self, err); }

static_assert(wcs::shim::nsdm_offset<^^::csharp_cases::Terrain>(1) == 24, "welder: erased-field offset drift: bones");

void welder_csharp_cases_Terrain_set_bones(void* self, void* v, welder_error* err) { return wcs::shim::field_set<^^::csharp_cases::Terrain, wcs::named_field(^^::csharp_cases::Terrain, "bones")>(self, err, v); }

void* welder_vec_std_vector_csharp_cases_Point_new(welder_error* err) { return wcs::shim::vec_new<^^::std::vector<::csharp_cases::Point>>(err); }

void welder_vec_std_vector_csharp_cases_Point_destroy(void* self) { wcs::shim::vec_destroy<^^::std::vector<::csharp_cases::Point>>(self); }

std::int64_t welder_vec_std_vector_csharp_cases_Point_size(void* self, welder_error* err) { return wcs::shim::vec_size<^^::std::vector<::csharp_cases::Point>>(self, err); }

void* welder_vec_std_vector_csharp_cases_Point_get(void* self, std::int64_t i, welder_error* err) { return wcs::shim::vec_get<^^::std::vector<::csharp_cases::Point>>(self, i, err); }

void welder_vec_std_vector_csharp_cases_Point_set(void* self, std::int64_t i, void* elem, welder_error* err) { wcs::shim::vec_set<^^::std::vector<::csharp_cases::Point>>(self, i, elem, err); }

void welder_vec_std_vector_csharp_cases_Point_add(void* self, void* elem, welder_error* err) { wcs::shim::vec_add<^^::std::vector<::csharp_cases::Point>>(self, elem, err); }

void welder_vec_std_vector_csharp_cases_Point_clear(void* self, welder_error* err) { wcs::shim::vec_clear<^^::std::vector<::csharp_cases::Point>>(self, err); }

static_assert(wcs::shim::nsdm_offset<^^::csharp_cases::Terrain>(2) == 48, "welder: erased-field offset drift: clusters");

void welder_csharp_cases_Terrain_set_clusters(void* self, void* v, welder_error* err) { return wcs::shim::field_set<^^::csharp_cases::Terrain, wcs::named_field(^^::csharp_cases::Terrain, "clusters")>(self, err, v); }

std::int32_t welder_csharp_cases_Terrain_m_weight_0(void* self, std::int32_t a0, std::int32_t a1, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Terrain, wcs::named_member(^^::csharp_cases::Terrain, "weight", 0)>(self, err, a0, a1); }

std::int32_t welder_csharp_cases_Terrain_m_bone_0(void* self, std::int32_t a0, std::int32_t a1, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Terrain, wcs::named_member(^^::csharp_cases::Terrain, "bone", 0)>(self, err, a0, a1); }

std::int32_t welder_csharp_cases_Terrain_m_cluster_x_0(void* self, std::int32_t a0, std::int32_t a1, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Terrain, wcs::named_member(^^::csharp_cases::Terrain, "cluster_x", 0)>(self, err, a0, a1); }

void welder_csharp_cases_Catalog_destroy(void* self) { wcs::shim::destroy<^^::csharp_cases::Catalog>(self); }

void* welder_csharp_cases_Catalog_new_default(welder_error* err) { return wcs::shim::default_construct<^^::csharp_cases::Catalog>(err); }

void* welder_csharp_cases_Catalog_clone(void* self, welder_error* err) { return wcs::shim::clone<^^::csharp_cases::Catalog>(self, err); }

welder_seq_wire welder_csharp_cases_Catalog_get_entries(void* self, welder_error* err) { return wcs::shim::field_get<^^::csharp_cases::Catalog, wcs::named_field(^^::csharp_cases::Catalog, "entries")>(self, err); }

void welder_csharp_cases_Catalog_set_entries(void* self, welder_seq_wire v, welder_error* err) { return wcs::shim::field_set<^^::csharp_cases::Catalog, wcs::named_field(^^::csharp_cases::Catalog, "entries")>(self, err, v); }

welder_seq_wire welder_csharp_cases_Catalog_get_pair(void* self, welder_error* err) { return wcs::shim::field_get<^^::csharp_cases::Catalog, wcs::named_field(^^::csharp_cases::Catalog, "pair")>(self, err); }

void welder_csharp_cases_Catalog_set_pair(void* self, welder_seq_wire v, welder_error* err) { return wcs::shim::field_set<^^::csharp_cases::Catalog, wcs::named_field(^^::csharp_cases::Catalog, "pair")>(self, err, v); }

welder_seq_wire welder_csharp_cases_Catalog_m_shout_0(void* self, welder_seq_wire a0, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Catalog, wcs::named_member(^^::csharp_cases::Catalog, "shout", 0)>(self, err, a0); }

std::int32_t welder_csharp_cases_Catalog_m_entry_count_0(void* self, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Catalog, wcs::named_member(^^::csharp_cases::Catalog, "entry_count", 0)>(self, err); }

welder_seq_wire welder_csharp_cases_f_split_words_0(const char* a0, welder_error* err) { return wcs::shim::function<wcs::named_member(^^::csharp_cases, "split_words", 0)>(err, a0); }

void welder_csharp_cases_WoodCrate_destroy(void* self) { wcs::shim::destroy<^^::csharp_cases::WoodCrate>(self); }

void* welder_csharp_cases_WoodCrate_new_default(welder_error* err) { return wcs::shim::default_construct<^^::csharp_cases::WoodCrate>(err); }

void* welder_csharp_cases_WoodCrate_clone(void* self, welder_error* err) { return wcs::shim::clone<^^::csharp_cases::WoodCrate>(self, err); }

std::int32_t welder_csharp_cases_WoodCrate_m_weigh_0_at_csharp_cases_CrateBase_csharp_cases_Wood(void* self, std::int32_t a0, welder_error* err) { return wcs::shim::method<^^::csharp_cases::WoodCrate, wcs::named_member(wcs::base_scope(^^::csharp_cases::WoodCrate, "csharp_cases_CrateBase_csharp_cases_Wood"), "weigh", 0)>(self, err, a0); }

static_assert(wcs::shim::nsdm_offset<^^::csharp_cases::WoodCrate>(0) == 0, "welder: erased-field offset drift: stamped");

std::int32_t welder_csharp_cases_WoodCrate_m_weigh_0(void* self, welder_error* err) { return wcs::shim::method<^^::csharp_cases::WoodCrate, wcs::named_member(^^::csharp_cases::WoodCrate, "weigh", 0)>(self, err); }

std::int32_t welder_csharp_cases_inner_f_twice_0(std::int32_t a0, welder_error* err) { return wcs::shim::function<wcs::named_member(^^::csharp_cases::inner, "twice", 0)>(err, a0); }

void welder_free(void* p) { std::free(p); }

const char* welder_dup_utf8(const char* s) { return wcs::shim::dup(s ? s : ""); }

// The ERASED-FIELD entry points: shared by every erased data-member property.
// The offsets arrive from the managed side (generator-computed); the per-member
// static_asserts in the shim shards verify them on this platform's ABI.
static void welder__field_ok(welder_error* e) { e->code = 0; e->message = nullptr; }

std::int8_t welder__field_get_sbyte(void* self, std::int32_t off, welder_error* err) { welder__field_ok(err); return *reinterpret_cast<const std::int8_t*>(static_cast<const char*>(self) + off); }
void welder__field_set_sbyte(void* self, std::int32_t off, std::int8_t v, welder_error* err) { welder__field_ok(err); *reinterpret_cast<std::int8_t*>(static_cast<char*>(self) + off) = v; }
std::uint8_t welder__field_get_byte(void* self, std::int32_t off, welder_error* err) { welder__field_ok(err); return *reinterpret_cast<const std::uint8_t*>(static_cast<const char*>(self) + off); }
void welder__field_set_byte(void* self, std::int32_t off, std::uint8_t v, welder_error* err) { welder__field_ok(err); *reinterpret_cast<std::uint8_t*>(static_cast<char*>(self) + off) = v; }
std::int16_t welder__field_get_short(void* self, std::int32_t off, welder_error* err) { welder__field_ok(err); return *reinterpret_cast<const std::int16_t*>(static_cast<const char*>(self) + off); }
void welder__field_set_short(void* self, std::int32_t off, std::int16_t v, welder_error* err) { welder__field_ok(err); *reinterpret_cast<std::int16_t*>(static_cast<char*>(self) + off) = v; }
std::uint16_t welder__field_get_ushort(void* self, std::int32_t off, welder_error* err) { welder__field_ok(err); return *reinterpret_cast<const std::uint16_t*>(static_cast<const char*>(self) + off); }
void welder__field_set_ushort(void* self, std::int32_t off, std::uint16_t v, welder_error* err) { welder__field_ok(err); *reinterpret_cast<std::uint16_t*>(static_cast<char*>(self) + off) = v; }
std::int32_t welder__field_get_int(void* self, std::int32_t off, welder_error* err) { welder__field_ok(err); return *reinterpret_cast<const std::int32_t*>(static_cast<const char*>(self) + off); }
void welder__field_set_int(void* self, std::int32_t off, std::int32_t v, welder_error* err) { welder__field_ok(err); *reinterpret_cast<std::int32_t*>(static_cast<char*>(self) + off) = v; }
std::uint32_t welder__field_get_uint(void* self, std::int32_t off, welder_error* err) { welder__field_ok(err); return *reinterpret_cast<const std::uint32_t*>(static_cast<const char*>(self) + off); }
void welder__field_set_uint(void* self, std::int32_t off, std::uint32_t v, welder_error* err) { welder__field_ok(err); *reinterpret_cast<std::uint32_t*>(static_cast<char*>(self) + off) = v; }
std::int64_t welder__field_get_long(void* self, std::int32_t off, welder_error* err) { welder__field_ok(err); return *reinterpret_cast<const std::int64_t*>(static_cast<const char*>(self) + off); }
void welder__field_set_long(void* self, std::int32_t off, std::int64_t v, welder_error* err) { welder__field_ok(err); *reinterpret_cast<std::int64_t*>(static_cast<char*>(self) + off) = v; }
std::uint64_t welder__field_get_ulong(void* self, std::int32_t off, welder_error* err) { welder__field_ok(err); return *reinterpret_cast<const std::uint64_t*>(static_cast<const char*>(self) + off); }
void welder__field_set_ulong(void* self, std::int32_t off, std::uint64_t v, welder_error* err) { welder__field_ok(err); *reinterpret_cast<std::uint64_t*>(static_cast<char*>(self) + off) = v; }
float welder__field_get_float(void* self, std::int32_t off, welder_error* err) { welder__field_ok(err); return *reinterpret_cast<const float*>(static_cast<const char*>(self) + off); }
void welder__field_set_float(void* self, std::int32_t off, float v, welder_error* err) { welder__field_ok(err); *reinterpret_cast<float*>(static_cast<char*>(self) + off) = v; }
double welder__field_get_double(void* self, std::int32_t off, welder_error* err) { welder__field_ok(err); return *reinterpret_cast<const double*>(static_cast<const char*>(self) + off); }
void welder__field_set_double(void* self, std::int32_t off, double v, welder_error* err) { welder__field_ok(err); *reinterpret_cast<double*>(static_cast<char*>(self) + off) = v; }
bool welder__field_get_bool(void* self, std::int32_t off, welder_error* err) { welder__field_ok(err); return *reinterpret_cast<const bool*>(static_cast<const char*>(self) + off); }
void welder__field_set_bool(void* self, std::int32_t off, bool v, welder_error* err) { welder__field_ok(err); *reinterpret_cast<bool*>(static_cast<char*>(self) + off) = v; }
void* welder__field_addr(void* self, std::int32_t off, welder_error* err) { welder__field_ok(err); return static_cast<char*>(self) + off; }
const char* welder__field_get_str(void* self, std::int32_t off, welder_error* err) { return wcs::shim::caught<const char*>(err, [&]() -> const char* { return wcs::shim::dup(reinterpret_cast<const ::std::string*>(static_cast<const char*>(self) + off)->c_str()); }); }
void welder__field_set_str(void* self, std::int32_t off, const char* v, welder_error* err) { wcs::shim::caught<int>(err, [&]() -> int { *reinterpret_cast<::std::string*>(static_cast<char*>(self) + off) = v ? v : ""; return 0; }); }

} // extern "C"
